fn main() {
    windows::build!(
        windows::win32::system_services::{
            CreateEventW,
            GetModuleHandleW,
            SetEvent,
            WaitForSingleObject,
            CS_HREDRAW,
            CS_VREDRAW,
            IDI_APPLICATION,
            IDC_ARROW,
            WS_OVERLAPPEDWINDOW,
            WM_DESTROY,
            WM_QUIT,
            LRESULT,
            SW_NORMAL,
            HINSTANCE,
        },
        windows::win32::windows_and_messaging::{
            WNDCLASSW,
            HWND,
            LPARAM,
            WPARAM,
            MSG,
            RegisterClassW,
            CreateWindowExW,
            PostQuitMessage,
            DefWindowProcW,
            ShowWindow,
            GetMessageW,
            DispatchMessageW,
        },
        windows::win32::gdi::{
            HBRUSH,
            GetStockObject,
            UpdateWindow,
        },
        windows::win32::menus_and_resources::{
            LoadIconW,
            LoadCursorW,
            HMENU,
        },
        windows::win32::windows_programming::{
            CloseHandle,
        },
    );
}
